// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cwkzviympmjcdqmgyhik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3a3p2aXltcG1qY2RxbWd5aGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDk4MzgsImV4cCI6MjA3MDIyNTgzOH0.n23SDOUNT6p7uZwjLm2FE2rdoBQrm968lbhfwWNf1Oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});