name: Cron Job (DISABLED - Using refresh-data.yml instead)

# on:
#   schedule:
#     # Run every 2 hours
#     - cron: '0 */2 * * *'
#   workflow_dispatch: # Allow manual trigger

jobs:
  cron:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd api
          npm install
          
      - name: Run cron job
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          LEAGUE_STANDINGS_API_KEY: ${{ secrets.LEAGUE_STANDINGS_API_KEY }}
        run: |
          cd api
          node cron.js
          
      - name: Notify on failure
        if: failure()
        run: |
          echo "Cron job failed"